#!/bin/bash

clear;

CACHE=;

if [ ! -z $1 ] 
then 
    CACHE=$1
else
    CACHE=
fi

# Line 24: Install Git Secrets from https://github.com/awslabs/git-secrets.git.
# This can prevent committing passwords and other sensitive information 
# to a git repository.

docker image prune --force=true && \
docker stop $(docker ps -a -q) && \ 
docker rm $(docker ps -a -q); \ 
docker-compose up -d apache2 mysql phpmyadmin redis workspace && \ 
docker-compose build $CACHE && \ 
winpty docker-compose exec --user=root workspace bash -c "
	if [ -d git-secrets ]; then rm -Rf git-secrets; fi;
    git clone https://github.com/awslabs/git-secrets.git && cd git-secrets;
	make install; cd ../ && rm -rf git-secrets;
	git secrets --install -f && git secrets --scan-history; 
	php artisan migrate && php artisan db:seed;
	";