#!/bin/bash

clear;

docker image prune --force=true && \
docker stop $(docker ps -a -q) && \ 
docker rm $(docker ps -a -q); \ 
docker-compose up -d apache2 mysql phpmyadmin redis workspace;

if [ "$1" == "--no-cache" ] 
then
    echo "Building Docker image with cache..."; sleep 2;
    docker-compose build --no-cache;
else
    echo "Building Docker image without cache..."; sleep 2;
    docker-compose build;
fi;

winpty docker-compose exec --user=root workspace bash -c "
	if [ -d git-secrets ]; then rm -Rf git-secrets; fi;
    git clone https://github.com/awslabs/git-secrets.git && cd git-secrets;
	make install; cd ../ && rm -rf git-secrets;
	chown -R laradock:www-data /var/www/*;
	git secrets --install -f && git secrets --scan-history;
    "
	
winpty docker-compose exec --user=laradock workspace bash -c "
    composer install && composer dump-autoload --optimize;	
	php artisan migrate && php artisan db:seed;
	yarn install --force;
	";